"""
Django settings for projeto_02 project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv 
import os

load_dotenv(os.path.join(BASE_DIR, '.env'))

CHAVE_DJANGO = os.getenv('chave_django')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CHAVE_DJANGO

# Seguridade: recursos especiais para desenvolvedores de depuração
DEBUG = True

#09 Permitindo acesso local para desenvolvimento em DEBUG=False
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  #09 Adicionando a aplicação core
    'bootstrap4',  #09 Adicionando bootstrap4 para estilização
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  #09 Middleware para publicação na produção
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projeto_02.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],  #09 Diretório para templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto_02.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



ENGINE = os.getenv('engine')
NOME_DO_BANCO = os.getenv('nome_do_banco')
MEU_USUARIO = os.getenv('meu_usuario')
MINHA_SENHA = os.getenv('minha_senha')
PORTA = os.getenv('porta')


DATABASES = {
    'default': {
        'ENGINE': ENGINE, #09 Usando MySQL como banco de dados
        'NAME': NOME_DO_BANCO, #09 Nome do banco de dados
        'USER': MEU_USUARIO, #09 Usuário do banco de dados
        'PASSWORD': MINHA_SENHA, #09 Senha do banco de dados
        'HOST': 'localhost', #09 Host do banco de dados
        'PORT': PORTA, #09 Porta do banco de dados
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' #09 Definindo o idioma para português do Brasil

TIME_ZONE = 'America/Sao_Paulo' #09 Definindo o fuso horário para São Paulo

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' #09 Diretório para arquivos estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' #09 Configuração para servir arquivos estáticos em produção 
MEDIA_URL = 'media/'  #11 URL para arquivos de mídia
MEDIA_ROOT = BASE_DIR / 'media'  #11 Diretório para arquivos de mídia


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#11 Configuração para servir arquivos de mídia (Django Admin)
LOGOUT_REDIRECT_URL = 'index'  #11 Redirecionar para a página inicial após logout

#12 Configuração de email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Teste de envio (Saida no terminal)

#12 Para enviar e-mails reais, descomete as linhas abaixo e configure com suas credenciais de e-mail
# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = '' # seu e-mail
# EMAIL_HOST_PASSWORD = '' # sua senha de e-mail
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

